service: ats-zoho-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10
  region: ap-south-1
  stage: dev
  environment:
    ZOHO_ACCESS_TOKEN: ${env:ZOHO_ACCESS_TOKEN}

functions:
  getJobs:
    handler: handlers/getJobs.handler
    events:
      - http:
          path: jobs
          method: get
          cors: true

  createCandidate:
    handler: handlers/createCandidate.handler
    events:
      - http:
          path: candidates
          method: post
          cors: true

  getApplications:
    handler: handlers/getApplications.handler
    events:
      - http:
          path: applications
          method: get
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
