service: ats-zoho-service



provider:
  name: aws
  runtime: python3.9
  region: ap-south-1
  timeout: 30
  environment:
    ZOHO_BASE_URL: https://people.zoho.in/people/api
    ZOHO_ACCESS_TOKEN: ${env:ZOHO_ACCESS_TOKEN}

functions:
  getJobs:
    handler: handlers/jobs.handler
    events:
      - httpApi:
          path: /jobs
          method: GET

  createCandidate:
    handler: handlers/candidates.handler
    events:
      - httpApi:
          path: /candidates
          method: POST

  getApplications:
    handler: handlers/applications.handler
    events:
      - httpApi:
          path: /applications
          method: GET

plugins:
  - serverless-offline
